### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by shah0150** [TwilioDevEd/appointment-reminders-flask#6]
Hello,

I tried to deploy this code on Heroku, but it showed me an Application Error. "

2016-03-07T00:17:16.446416+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=zakapp.herokuapp.com request_id=84706f2e-353c-4ad2-8885-8187f63303aa fwd="99.246.125.65" dyno= connect= service= status=503 bytes=

2016-03-07T00:17:10+00:00 app[heroku-redis]: source=REDIS sample#active-connections=1 sample#load-avg-1m=0.325 sample#load-avg-5m=0.33 sample#load-avg-15m=0.24 sample#read-iops=0 sample#write-iops=0 sample#memory-total=15405632.0kB sample#memory-free=13360600.0kB sample#memory-cached=527152kB sample#memory-redis=294048bytes sample#hit-rate=1 sample#evicted-keys=0

2016-03-07T00:17:31.687322+00:00 heroku[worker.1]: State changed from crashed to starting

2016-03-07T00:17:34.624612+00:00 heroku[worker.1]: Starting process with command `celery -A reminders.celery worker -l info`

2016-03-07T00:17:35.237161+00:00 heroku[worker.1]: State changed from starting to up

2016-03-07T00:17:36.373802+00:00 app[worker.1]: Traceback (most recent call last):

2016-03-07T00:17:36.373819+00:00 app[worker.1]:   File "/app/.heroku/python/bin/celery", line 7, in <module>
2016-03-07T00:17:36.373970+00:00 app[worker.1]:     from celery import five

2016-03-07T00:17:36.373972+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/utils/__init__.py", line 19, in <module>

2016-03-07T00:17:36.373974+00:00 app[worker.1]:     from uuid import UUID, uuid4 as _uuid4, _uuid_generate_random

2016-03-07T00:17:36.374010+00:00 app[worker.1]: ImportError: cannot import name _uuid_generate_random

2016-03-07T00:17:37.174982+00:00 heroku[worker.1]: State changed from up to crashed

2016-03-07T00:17:37.145990+00:00 heroku[worker.1]: Process exited with status 1

Thanks,
Adesh

**Comment by officerebel** [comment]
same here
